### ISSUE TITLE
dataset acquire

### ISSUE THREAD

**Issue by renyu2016** [XiaoshuiHuang/CSBaselineAlgo#1]
Could the author provide a download link for acquiring the 3DCSR dataset? Thanks a lot!

**Comment by XiaoshuiHuang** [comment]
The website has got some issues. We are solving the technical issues and will make the website online soon. I will give an update to you when the website is alive.

**Comment by renyu2016** [comment]
> The website has got some issues. We are solving the technical issues and will make the website online soon. I will give an update to you when the website is alive.

Appreciate

**Comment by renyu2016** [comment]
> Hi, the website is alive now. You can access the dataset at http://multimediauts.org/3D_data_for_registration/

Thanks a lot again！
